replicaCount: 1

config:
  servers:
    listings:
      DEPLOYOVER: jdbc://guest@deployover.com:8521/db
      JDKENDALL: jdbc://admin@jdkendall.com:9931/fake
      SOMEWHERE: jdbc://aslan@narnia:1212/wardrobe

serviceAccount:
  create: true

image:
  repository: localhost:5000/mountyaml
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

